name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  local:
    name: "test on hosted runner (Ruby=${{ matrix.ruby }}, runner=${{ matrix.runner }})"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 2.3
        runner:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: bundle update
        run: |
          set -xe
          bundle config --local path $PWD/vendor/bundle
          bundle config --local jobs $(nproc)
          bundle update --retry 3

      - name: Run test
        run: bundle exec rake test:local

  docker:
    name: "test on docker (Ruby=${{ matrix.ruby }}, test_task=${{ matrix.test_task }}, image=${{ matrix.image }})"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 2.3
        image:
          - debian:bullseye
          - debian:bookworm
          - amazonlinux:2
          - ubuntu:focal
          - ubuntu:jammy
        test_task:
          - test:docker_system
          - test:docker_user

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: bundle update
        run: |
          set -xe
          bundle config --local path $PWD/vendor/bundle
          bundle config --local jobs $(nproc)
          bundle update --retry 3

      - name: Run test
        run: bundle exec rake ${TEST_TASK}
        env:
          SOURCE_IMAGE: ${{ matrix.image }}
          TEST_TASK: ${{ matrix.test_task }}
